#!/usr/bin/env ruby
# encoding: UTF-8
require File.dirname(__FILE__) + '/lib/zwoelftonspielzeug'
include Hauer::Utils
@a = Zwoelftonspielzeug::Automat.new
@spiel = @a.spiel
@p = @a.proxy

puts <<HILFE

☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ ☯ ♫ 

  Willkommen beim Zwölftonspielzeug - Frei nach den Erkenntnissen von 
  Joseph Matthias Hauer, dem Erfinder der Zwölftonmusik.  

  Wir starten mit einer Reihe aus J.M. Hauers Zwölftonspiel für 
  Cembalo oder Klavier vom 11. Juni 1955.
    @spiel.reihe = #{@spiel.reihe.inspect}
  (Das sind MIDI Töne…)
  
HILFE
# == Verschiedene Reihen
# Reihe aus J.M. Hauers Zwölftonspiel für Cembalo oder Klavier 11. Juni 1955
@spiel.reihe = [57, 51, 48, 47, 55, 56, 49, 52, 46, 54, 53, 50]

# Reihe aus J.M. Hauers Zwölftonspiel für Flöte und Cembalo vom 31. August 1948
# @spiel.reihe = [59, 49, 50, 58, 56, 53, 51, 54, 57, 52, 48, 55]
#
# Reihe aus "Passacaglia für Klavier" von einer Bamberger Gymnasialklasse 1974
# http://www.musiker.at/sengstschmidjohann/mp3/sonstiges/passacaglia.mp3
# http://www.klangreihenmusik.at/skriptum-passacaglia-01kl.php3
@spiel.reihe = [52, 55, 49, 50, 58, 48, 53, 57, 54, 51, 59, 56]
#
# Zufällig gewählte Reihe
# @spiel.reihe = (60..71).to_a.shuffle

# == Eigentschaften des Spiels ändern
# @stimmen[3] = proc { Hauer::Arpeggiator.arpeggio!(@spiel.klangreihe, :reverse => @spiel.akkordkrebs?) } #, :arp => 0.1
# @spiel.akkordkrebs = true
# @spiel.umkehrung = 2 
@a.stimmvariation!(:sopran, 5)
system "open #{File.expand_path(File.dirname(__FILE__))}/pd/start.pd"
puts "Bitte öffne pd/start.pd"
puts "Drücke die ↵ [Enter] Taste oder gebe vorher ein neues Tempo (jetzt: 80) ein um zu starten."
tempo = gets.to_i
tempo = tempo > 0 ? tempo : 80
puts "䷎"
# CLI
puts "'stop' um das Spiel zu beenden."
def stop
  puts "stoppe..."
  @a.stop
end
def spiel
  @spiel
end
def stimmen
  @stimmen
end

@a.start(tempo)
# @a.scheduler.join

# Live coding!
loop do  
  begin
    eval gets
  rescue    
    puts "???"
  end
end